print("How old are you?")
age = input()
print("When is your DoB?")
dob = input()
print("Your are " + age + " and your DoB is " + dob)
print("age is:")
print(type(age))
print("dob is:")
print(type(dob))
